// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  variable: "--font-chakra-petch",
  display: "swap",
});

const normalidad = localFont({
  src: [
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Bold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/normalidad/Normalidad_UltraExtended_Thin.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-normalidad",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${normalidad.variable} ${chakraPetch.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
